### ISSUE TITLE
窗长度、DCRNN-CL的问题

### ISSUE THREAD

**Issue by Rafeal23** [huyanxin/DeepComplexCRN#1]
您好，文章中几处细节有些不理解。

1. 文章中说选取窗长度=25ms，fs=16kHz，每个窗包含400个数据，做512点的FFT。
请问此处是对400个数据进行补0扩充到512点做FFT吗？如果是，为什么不选取更长的窗（如32ms,512个数据无需补0）进行处理？
2. “DCCRN-CL(masking like DCCRN-E)”，是指按照公式（8）进行计算，DCCRN-CL的mask值是受限在0~1，而DCCRN-C的mask无限制范围吗？
3. “The direct current component of all these models is removed.” 模型中的直流分量指的是什么？这样做的意义是什么？

希望得到您的答复。

**Comment by MaNatsu8023** [comment]
1.是对400个点进行补零扩充到512做fft, 我们进行了各种尝试（更长和更短）发现这个配置比较好。
2.DCCRN-CL和DCCRN-E都是使用tanh限制幅度（mag）的mask到0，1，而DCCRN-C是实部和虚部的mask，没有进行限制，转化到极坐标下的目的就是为了进行mask限制。后来我们发现进行限制效果比较好，所以DCCRN-CL没有写没有限制的情况。
3.直流分量没有啥用，对stft并没有什么影响，比如一个16000长的语音所以进行512个点的librosa.stft之后的得到大小(257,126)的矩阵，其中第一行就是直流分量，你可以选择把第一行舍掉，得到（256，126）的矩阵。这里这么做主要是为了卷积好凑，加上也没有影响。你可以尝试进行stft之后把直流分量置零，然后进行逆stft，你会发现变换前和变换后的误差和留下直流分量是差不多的。

**Comment by Rafeal23** [comment]
明白了！谢谢您的回复！
