### ISSUE TITLE
Test time over CPU

### ISSUE THREAD

**Issue by sunwell1994** [huyanxin/DeepComplexCRN#17]
As the paper claimed, one frame takes around 3.12 ms. How does this number come from? Thanks for sharing the experience.

**Comment by huyanxin** [comment]
OK. The rough process is shown below:
1. converting the model to onnx, maybe like `torch.atan2` or other modules can not be converted, just remove (i)stft and this part from the model. Only use the onnx to predict cirm. As for those modules, they can be implemented by numpy 
2. Single thread mode, follow this https://github.com/microsoft/onnxruntime/issues/3233
3. In testing, we feed the model with 1 frame, 10 frames, 50 frames and 100 frames for 10000 times. To balance cache and GEMM, we select 10 frames or 50 frames 's inferencing time as the final results.
Of course, above is just to record `forward time` in an easy way. In inference mode, the CNNs need buffer to store context information to ensure the training and evaluation completely consistent. The implementation of this part is related to the inference framework used,  so I won't give unnecessary details here.

**Comment by sunwell1994** [comment]
Thanks for details
