### ISSUE TITLE
关于实时推理的一些细节

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [huyanxin/DeepComplexCRN#18]
您好，我刚入门语音处理不久，最近在复现贵团队的DCCRN模型。我使用您论文中提到的训练参数，将DNS challenge数据集中的音频分为每段15s去训练。使用训练得到的模型对完整的音频文件进行测试，出来的效果没有问题非常好。
然后为了测试其实时推理的效果，我将音频文件切分为每37.5ms一个clip，然后将这些clips按照时序送入网络，得到网络的输出后再按照时序进行拼接，最后得到完整的处理后的音频。在推理的过程中我在您提供的官方模型代码的基础上修改和添加了：
（1）将“stft左右两边各补300采样点的零”改为“左边补300采样点的前一帧末尾的数据，右边补300采样点的零”
（2）手动更新LSTM的状态h和c
（3）给encoder添加buffer。即将前一帧的6次encoder的输入的（时序维度上）最后一个特征作为当前帧6次encoder时padding的内容（而不是padding零）
然而基于以上操作进行推理，出来的音频效果并不好（几乎没有降噪效果）。
因为网络对完整的音频文件进行推理出来的效果很好，所以可以确定网络的训练是有效的。而使用clip的方法去推理效果不好，我觉得可能还是推理的部分哪里没有和训练部分保持一致。
请问是我对您提供的官方模型代码进行修改和添加的过程中出现了错误，还是说我还需要再对代码进行一些其它修改？

**Comment by KAWAKO-in-GAYHUB** [comment]
> > 非常感谢！！！ 因为之后想将网络移植到边缘设备上，所以我将stft与istft过程从网络中剥离了出来（单独用librosa去做），然后我对转置卷积添加了buffer，手动更新了LSTM的状态，最终对比流式推理与整句推理的结果相同，说明这样修改没有问题。只是修改之后的推理过程确实相对复杂，想在边缘设备的cpu上达到实时还是有些困难。
> 
> 我今天也在思考这个问题，有代码可以参考一下吗？

我的代码目前也有些混乱，并且虽然网络输出是对的但是istft部分还存在一些问题。等将istft部分的问题解决并且将代码整理好以后可以考虑把代码放出来，你也可以期待一下作者的这部分代码。

**Comment by bayleef1** [comment]
> 非常感谢！！！ 因为之后想将网络移植到边缘设备上，所以我将stft与istft过程从网络中剥离了出来（单独用librosa去做），然后我对转置卷积添加了buffer，手动更新了LSTM的状态，最终对比流式推理与整句推理的结果相同，说明这样修改没有问题。只是修改之后的推理过程确实相对复杂，想在边缘设备的cpu上达到实时还是有些困难。

您好，转置卷积添加buffer可以讲详细一些吗，和encoder添加buffer有哪些不同？

**Comment by KAWAKO-in-GAYHUB** [comment]
> > 非常感谢！！！ 因为之后想将网络移植到边缘设备上，所以我将stft与istft过程从网络中剥离了出来（单独用librosa去做），然后我对转置卷积添加了buffer，手动更新了LSTM的状态，最终对比流式推理与整句推理的结果相同，说明这样修改没有问题。只是修改之后的推理过程确实相对复杂，想在边缘设备的cpu上达到实时还是有些困难。
> 
> 您好，转置卷积添加buffer可以讲详细一些吗，和encoder添加buffer有哪些不同？

大概思路就是：
（1）每次卷积结束后把结果保存进buffer。
（2）做完lstm之后创建一个空的buffer，将lstm的结果放到末尾，这个buffer用于下一步做转置卷积。
（3）在转置卷积环节，先把（2）的buffer与（1）的buffer进行拼接然后再做转置卷积，每次转置卷积后扔掉头部数据然后再做下一次转置卷积。
按照上面的思路去做（要注意数据的对齐）的话，每次推理会有7帧结果，由于转置卷积默认在数据两端进行了补零，所以只有第1帧结果是可用的。
这个方法应该不是最优方法😂但输出的第1帧结果我测试过是正确的。

**Comment by lhwcv** [comment]
@KAWAKO-in-GAYHUB  你好， nice work！ 这部分的代码能分享下吗。
