### ISSUE TITLE
关于mask_phase的计算公式问题

### ISSUE THREAD

**Issue by zhiyuzhang-0212** [huyanxin/DeepComplexCRN#28]
![ALUX@MD6VRI{Q_PC}0YV7C](https://github.com/huyanxin/DeepComplexCRN/assets/84052294/a477c140-75a4-4e3d-9db2-7d9eb01385fa)
论文公式里计算mask_phase的方式是直接对网络的输出求arctan，为什么在代码实现里多了一步求real_phase，imag_phase这一步呢？代码实现如下：
![8()R0V`FE4UK`N@){SN}N)H](https://github.com/huyanxin/DeepComplexCRN/assets/84052294/48acae5f-3315-4ede-a156-5ee7daf4f545)

**Comment by huyanxin** [comment]
我理解本质上两个没有差别，只是单纯为了保证数值稳定，避免atan2出现nan的问题，你也可以试试下面这种方式
```
def sign_clamp(inputs, min):
   mag = inputs.abs()
   with torch.no_grad():
       sign = torch.sign(inputs)
       sign = torch.where(sign == 0, min, sign)
   outputs = torch.clamp(mag, min)*sign
   return outputs
phase = torch.atan2(mask_imag, sign_clamp(mask_real,1e-8))
```

**Comment by zhiyuzhang-0212** [comment]
> 我理解本质上两个没有差别，只是单纯为了保证数值稳定，避免atan2出现nan的问题，你也可以试试下面这种方式
> 
> ```
> def sign_clamp(inputs, min):
>    mag = inputs.abs()
>    with torch.no_grad():
>        sign = torch.sign(inputs)
>        sign = torch.where(sign == 0, min, sign)
>    outputs = torch.clamp(mag, min)*sign
>    return outputs
> phase = torch.atan2(mask_imag, sign_clamp(mask_real,1e-8))
> ```

非常感谢！
