### ISSUE TITLE
ComplexLSTM和Dense的问题

### ISSUE THREAD

**Issue by ZeHuangFang** [huyanxin/DeepComplexCRN#3]
你好，祝贺贵团队在DNS challenge中获得好成绩。
在对贵团队的论文进行复现的过程中，我遇到了以下几个问题，渴求能够得到解答：

1、在ComplexEncoder和ComplexLSTM连接时的维度问题？
ComplexEncoder最后输出的结果应该为4维（batch, channel, H, W）,而ComplexLSTM的输入要求是（batch， timestep，feature_dim）,请问这边是如何处理匹配的呢？

2、在ComplexLSTM后面紧接着Dense层，但是此时的LSTM已经是复数形式，Dense层如何和其进行匹配？

3、Dense层的输出同样为3维（batch， timestep，feature_dim），请问贵团队是如何处理恢复成4维（batch, channel, H, W）以匹配ComplexDecoder的呢？

望解答，再次感谢贵团队的贡献！

**Comment by huyanxin** [comment]
非常感谢你的关注，
你的问题其实可以归为一个。整体是这样的
论文encoder出来后是[B,256,4,T] reshape后是[B,1024,T], 过完256的lstm后是[B,256,T], 所以需要有一个升采样的操作，我为了简便，直接用一个256到1024的Dense/Linear层进行一个矩阵乘，经过reshape 后就是[B,256,4,T] 了，考虑到矩阵乘是线性的，其实也没有加任何的非线性单元，所以认为信息是无损流动，所以就没有再做complex op了。
这部分本质上还是做一个维度变换，如果不加lieanr/dense layer的话，其实你也可以考虑直接做1024的lstm或者卷积层，不过实际上1x1卷积本质也是个linear，所以再换的意义也不大。
希望对你有帮助。

**Comment by ZeHuangFang** [comment]
感谢回复！
根据你的思路，dense层是作为一个上采样操作，那么意思是实部和虚部都通过同一个dense层进行上采样的是吗？

**Comment by huyanxin** [comment]
对，论文里用实数lstm的话我是直接用一个dense layer做的，简单复数的lstm是用分开的

**Comment by ZeHuangFang** [comment]
你好，又来叨扰~
抱歉，我太菜了，我用同样的数据量，按照论文给的参数，训练出来的效果始终比DCUnet还要差，请问是我遗漏了什么吗?
可否提点一二，十分感谢！
