### ISSUE TITLE
Number of parameters reported in paper

### ISSUE THREAD

**Issue by jonashaag** [huyanxin/DeepComplexCRN#4]
Hi! I think the number of parameters reported in the paper are off.

For example, DCCRN-CL is reported as 32, 64, 128, 256, 256, 256 filters each with kernel size 5*2=10, for a total of 3.7M params. But isn't the number of params of the Conv2Ds roughly follows? (ignoring LSTM)

```
  in  *   ks  * out =     total
------+-------+-----+----------
Encoder
    1 * 5 * 2 *  32 =       320
   32 * 5 * 2 *  64 =    20,480
   64 * 5 * 2 * 128 =    81,920
  128 * 5 * 2 * 256 =   327,680
+ 256 * 5 * 2 * 256 =   655,360
+ 256 * 5 * 2 * 256 =   655,360
Decoder
+ 256 * 5 * 2 * 256 =   655,360
+ 512 * 5 * 2 * 256 = 1,310,720  (has skip conn input)
+ 512 * 5 * 2 * 256 = 1,310,720  (has skip conn input)
+ 512 * 5 * 2 * 128 =   655,360  (has skip conn input)
  256 * 5 * 2 *  64 =   163,840  (has skip conn input)
  128 * 5 * 2 *  32 =    40,960  (has skip conn input)
   64 * 5 * 2 *   1 =       640  (has skip conn input)
-------------------------------
                    = 5,878,720 COMPLEX params, i.e. 11,757,440 REAL params
```

**Comment by huyanxin** [comment]
Sorry, maybe there is something unclear. the real+imag = [32,64,128,256,256], 
the details is shown as:
encoder.0.0.real_kernel torch.Size([16, 1, 5, 2])
encoder.0.0.real_bias torch.Size([16])
encoder.0.0.imag_kernel torch.Size([16, 1, 5, 2])
encoder.0.0.imag_bias torch.Size([16])
encoder.0.1.Wrr torch.Size([16])
encoder.0.1.Wri torch.Size([16])
encoder.0.1.Wii torch.Size([16])
encoder.0.1.Br torch.Size([16])
encoder.0.1.Bi torch.Size([16])
encoder.0.2.weight torch.Size([1])
encoder.1.0.real_kernel torch.Size([32, 16, 5, 2])
encoder.1.0.real_bias torch.Size([32])
encoder.1.0.imag_kernel torch.Size([32, 16, 5, 2])
encoder.1.0.imag_bias torch.Size([32])
encoder.1.1.Wrr torch.Size([32])
encoder.1.1.Wri torch.Size([32])
encoder.1.1.Wii torch.Size([32])
encoder.1.1.Br torch.Size([32])
encoder.1.1.Bi torch.Size([32])
encoder.1.2.weight torch.Size([1])
encoder.2.0.real_kernel torch.Size([64, 32, 5, 2])
encoder.2.0.real_bias torch.Size([64])
encoder.2.0.imag_kernel torch.Size([64, 32, 5, 2])
encoder.2.0.imag_bias torch.Size([64])
encoder.2.1.Wrr torch.Size([64])
encoder.2.1.Wri torch.Size([64])
encoder.2.1.Wii torch.Size([64])
encoder.2.1.Br torch.Size([64])
encoder.2.1.Bi torch.Size([64])
encoder.2.2.weight torch.Size([1])
encoder.3.0.real_kernel torch.Size([128, 64, 5, 2])
encoder.3.0.real_bias torch.Size([128])
encoder.3.0.imag_kernel torch.Size([128, 64, 5, 2])
encoder.3.0.imag_bias torch.Size([128])
encoder.3.1.Wrr torch.Size([128])
encoder.3.1.Wri torch.Size([128])
encoder.3.1.Wii torch.Size([128])
encoder.3.1.Br torch.Size([128])
encoder.3.1.Bi torch.Size([128])
encoder.3.2.weight torch.Size([1])
encoder.4.0.real_kernel torch.Size([128, 128, 5, 2])
encoder.4.0.real_bias torch.Size([128])
encoder.4.0.imag_kernel torch.Size([128, 128, 5, 2])
encoder.4.0.imag_bias torch.Size([128])
encoder.4.1.Wrr torch.Size([128])
encoder.4.1.Wri torch.Size([128])
encoder.4.1.Wii torch.Size([128])
encoder.4.1.Br torch.Size([128])
encoder.4.1.Bi torch.Size([128])
encoder.4.2.weight torch.Size([1])
encoder.5.0.real_kernel torch.Size([128, 128, 5, 2])
encoder.5.0.real_bias torch.Size([128])
encoder.5.0.imag_kernel torch.Size([128, 128, 5, 2])
encoder.5.0.imag_bias torch.Size([128])
encoder.5.1.Wrr torch.Size([128])
encoder.5.1.Wri torch.Size([128])
encoder.5.1.Wii torch.Size([128])
encoder.5.1.Br torch.Size([128])
encoder.5.1.Bi torch.Size([128])
encoder.5.2.weight torch.Size([1])
decoder.0.0.real_kernel torch.Size([256, 128, 5, 2])
decoder.0.0.real_bias torch.Size([128])
decoder.0.0.imag_kernel torch.Size([256, 128, 5, 2])
decoder.0.0.imag_bias torch.Size([128])
decoder.0.1.Wrr torch.Size([128])
decoder.0.1.Wri torch.Size([128])
decoder.0.1.Wii torch.Size([128])
decoder.0.1.Br torch.Size([128])
decoder.0.1.Bi torch.Size([128])
decoder.0.2.weight torch.Size([1])
decoder.1.0.real_kernel torch.Size([256, 128, 5, 2])
decoder.1.0.real_bias torch.Size([128])
decoder.1.0.imag_kernel torch.Size([256, 128, 5, 2])
decoder.1.0.imag_bias torch.Size([128])
decoder.1.1.Wrr torch.Size([128])
decoder.1.1.Wri torch.Size([128])
decoder.1.1.Wii torch.Size([128])
decoder.1.1.Br torch.Size([128])
decoder.1.1.Bi torch.Size([128])
decoder.1.2.weight torch.Size([1])
decoder.2.0.real_kernel torch.Size([256, 64, 5, 2])
decoder.2.0.real_bias torch.Size([64])
decoder.2.0.imag_kernel torch.Size([256, 64, 5, 2])
decoder.2.0.imag_bias torch.Size([64])
decoder.2.1.Wrr torch.Size([64])
decoder.2.1.Wri torch.Size([64])
decoder.2.1.Wii torch.Size([64])
decoder.2.1.Br torch.Size([64])
decoder.2.1.Bi torch.Size([64])
decoder.2.2.weight torch.Size([1])
decoder.3.0.real_kernel torch.Size([128, 32, 5, 2])
decoder.3.0.real_bias torch.Size([32])
decoder.3.0.imag_kernel torch.Size([128, 32, 5, 2])
decoder.3.0.imag_bias torch.Size([32])
decoder.3.1.Wrr torch.Size([32])
decoder.3.1.Wri torch.Size([32])
decoder.3.1.Wii torch.Size([32])
decoder.3.1.Br torch.Size([32])
decoder.3.1.Bi torch.Size([32])
decoder.3.2.weight torch.Size([1])
decoder.4.0.real_kernel torch.Size([64, 16, 5, 2])
decoder.4.0.real_bias torch.Size([16])
decoder.4.0.imag_kernel torch.Size([64, 16, 5, 2])
decoder.4.0.imag_bias torch.Size([16])
decoder.4.1.Wrr torch.Size([16])
decoder.4.1.Wri torch.Size([16])
decoder.4.1.Wii torch.Size([16])
decoder.4.1.Br torch.Size([16])
decoder.4.1.Bi torch.Size([16])
decoder.4.2.weight torch.Size([1])
decoder.5.0.real_kernel torch.Size([32, 1, 5, 2])
decoder.5.0.real_bias torch.Size([1])
decoder.5.0.imag_kernel torch.Size([32, 1, 5, 2])
decoder.5.0.imag_bias torch.Size([1])
enhance1.real_lstm.weight_ih_l0 torch.Size([512, 512])
enhance1.real_lstm.weight_hh_l0 torch.Size([512, 128])
enhance1.real_lstm.bias_ih_l0 torch.Size([512])
enhance1.real_lstm.bias_hh_l0 torch.Size([512])
enhance1.imag_lstm.weight_ih_l0 torch.Size([512, 512])
enhance1.imag_lstm.weight_hh_l0 torch.Size([512, 128])
enhance1.imag_lstm.bias_ih_l0 torch.Size([512])
enhance1.imag_lstm.bias_hh_l0 torch.Size([512])
enhance2.real_lstm.weight_ih_l0 torch.Size([512, 128])
enhance2.real_lstm.weight_hh_l0 torch.Size([512, 128])
enhance2.real_lstm.bias_ih_l0 torch.Size([512])
enhance2.real_lstm.bias_hh_l0 torch.Size([512])
enhance2.imag_lstm.weight_ih_l0 torch.Size([512, 128])
enhance2.imag_lstm.weight_hh_l0 torch.Size([512, 128])
enhance2.imag_lstm.bias_ih_l0 torch.Size([512])
enhance2.imag_lstm.bias_hh_l0 torch.Size([512])
enhance2.r_trans.weight torch.Size([512, 128])
enhance2.r_trans.bias torch.Size([512])
enhance2.i_trans.weight torch.Size([512, 128])
enhance2.i_trans.bias torch.Size([512])
[*] Parameter Size: 3671917

the code will be open-source soon...

**Comment by jonashaag** [comment]
Thanks! That explains a lot :-) We have an implementation here: https://github.com/mpariente/asteroid/blob/master/asteroid/models/dccrnet.py

**Comment by kssk16** [comment]
@huyanxin  A quick question regarding the dense layer after the LSTM layer in DCCRN-CL. The paper mentions that a dense layer of 1024 neurons follows the LSTM layer. But as I could see from the structure mentioned, the dense layer in both real and imaginary part contains 128 neurons. 
Does DCCRN-CL (128 + 128) contain different number of neurons in the dense layer than DCCRN-E, DCCRN-R and DCCRN-C (1024) ?


> Sorry, maybe there is something unclear. the real+imag = [32,64,128,256,256],
> the details is shown as:
> encoder.0.0.real_kernel torch.Size([16, 1, 5, 2])
> encoder.0.0.real_bias torch.Size([16])
> encoder.0.0.imag_kernel torch.Size([16, 1, 5, 2])
> encoder.0.0.imag_bias torch.Size([16])
> encoder.0.1.Wrr torch.Size([16])
> encoder.0.1.Wri torch.Size([16])
> encoder.0.1.Wii torch.Size([16])
> encoder.0.1.Br torch.Size([16])
> encoder.0.1.Bi torch.Size([16])
> encoder.0.2.weight torch.Size([1])
> encoder.1.0.real_kernel torch.Size([32, 16, 5, 2])
> encoder.1.0.real_bias torch.Size([32])
> encoder.1.0.imag_kernel torch.Size([32, 16, 5, 2])
> encoder.1.0.imag_bias torch.Size([32])
> encoder.1.1.Wrr torch.Size([32])
> encoder.1.1.Wri torch.Size([32])
> encoder.1.1.Wii torch.Size([32])
> encoder.1.1.Br torch.Size([32])
> encoder.1.1.Bi torch.Size([32])
> encoder.1.2.weight torch.Size([1])
> encoder.2.0.real_kernel torch.Size([64, 32, 5, 2])
> encoder.2.0.real_bias torch.Size([64])
> encoder.2.0.imag_kernel torch.Size([64, 32, 5, 2])
> encoder.2.0.imag_bias torch.Size([64])
> encoder.2.1.Wrr torch.Size([64])
> encoder.2.1.Wri torch.Size([64])
> encoder.2.1.Wii torch.Size([64])
> encoder.2.1.Br torch.Size([64])
> encoder.2.1.Bi torch.Size([64])
> encoder.2.2.weight torch.Size([1])
> encoder.3.0.real_kernel torch.Size([128, 64, 5, 2])
> encoder.3.0.real_bias torch.Size([128])
> encoder.3.0.imag_kernel torch.Size([128, 64, 5, 2])
> encoder.3.0.imag_bias torch.Size([128])
> encoder.3.1.Wrr torch.Size([128])
> encoder.3.1.Wri torch.Size([128])
> encoder.3.1.Wii torch.Size([128])
> encoder.3.1.Br torch.Size([128])
> encoder.3.1.Bi torch.Size([128])
> encoder.3.2.weight torch.Size([1])
> encoder.4.0.real_kernel torch.Size([128, 128, 5, 2])
> encoder.4.0.real_bias torch.Size([128])
> encoder.4.0.imag_kernel torch.Size([128, 128, 5, 2])
> encoder.4.0.imag_bias torch.Size([128])
> encoder.4.1.Wrr torch.Size([128])
> encoder.4.1.Wri torch.Size([128])
> encoder.4.1.Wii torch.Size([128])
> encoder.4.1.Br torch.Size([128])
> encoder.4.1.Bi torch.Size([128])
> encoder.4.2.weight torch.Size([1])
> encoder.5.0.real_kernel torch.Size([128, 128, 5, 2])
> encoder.5.0.real_bias torch.Size([128])
> encoder.5.0.imag_kernel torch.Size([128, 128, 5, 2])
> encoder.5.0.imag_bias torch.Size([128])
> encoder.5.1.Wrr torch.Size([128])
> encoder.5.1.Wri torch.Size([128])
> encoder.5.1.Wii torch.Size([128])
> encoder.5.1.Br torch.Size([128])
> encoder.5.1.Bi torch.Size([128])
> encoder.5.2.weight torch.Size([1])
> decoder.0.0.real_kernel torch.Size([256, 128, 5, 2])
> decoder.0.0.real_bias torch.Size([128])
> decoder.0.0.imag_kernel torch.Size([256, 128, 5, 2])
> decoder.0.0.imag_bias torch.Size([128])
> decoder.0.1.Wrr torch.Size([128])
> decoder.0.1.Wri torch.Size([128])
> decoder.0.1.Wii torch.Size([128])
> decoder.0.1.Br torch.Size([128])
> decoder.0.1.Bi torch.Size([128])
> decoder.0.2.weight torch.Size([1])
> decoder.1.0.real_kernel torch.Size([256, 128, 5, 2])
> decoder.1.0.real_bias torch.Size([128])
> decoder.1.0.imag_kernel torch.Size([256, 128, 5, 2])
> decoder.1.0.imag_bias torch.Size([128])
> decoder.1.1.Wrr torch.Size([128])
> decoder.1.1.Wri torch.Size([128])
> decoder.1.1.Wii torch.Size([128])
> decoder.1.1.Br torch.Size([128])
> decoder.1.1.Bi torch.Size([128])
> decoder.1.2.weight torch.Size([1])
> decoder.2.0.real_kernel torch.Size([256, 64, 5, 2])
> decoder.2.0.real_bias torch.Size([64])
> decoder.2.0.imag_kernel torch.Size([256, 64, 5, 2])
> decoder.2.0.imag_bias torch.Size([64])
> decoder.2.1.Wrr torch.Size([64])
> decoder.2.1.Wri torch.Size([64])
> decoder.2.1.Wii torch.Size([64])
> decoder.2.1.Br torch.Size([64])
> decoder.2.1.Bi torch.Size([64])
> decoder.2.2.weight torch.Size([1])
> decoder.3.0.real_kernel torch.Size([128, 32, 5, 2])
> decoder.3.0.real_bias torch.Size([32])
> decoder.3.0.imag_kernel torch.Size([128, 32, 5, 2])
> decoder.3.0.imag_bias torch.Size([32])
> decoder.3.1.Wrr torch.Size([32])
> decoder.3.1.Wri torch.Size([32])
> decoder.3.1.Wii torch.Size([32])
> decoder.3.1.Br torch.Size([32])
> decoder.3.1.Bi torch.Size([32])
> decoder.3.2.weight torch.Size([1])
> decoder.4.0.real_kernel torch.Size([64, 16, 5, 2])
> decoder.4.0.real_bias torch.Size([16])
> decoder.4.0.imag_kernel torch.Size([64, 16, 5, 2])
> decoder.4.0.imag_bias torch.Size([16])
> decoder.4.1.Wrr torch.Size([16])
> decoder.4.1.Wri torch.Size([16])
> decoder.4.1.Wii torch.Size([16])
> decoder.4.1.Br torch.Size([16])
> decoder.4.1.Bi torch.Size([16])
> decoder.4.2.weight torch.Size([1])
> decoder.5.0.real_kernel torch.Size([32, 1, 5, 2])
> decoder.5.0.real_bias torch.Size([1])
> decoder.5.0.imag_kernel torch.Size([32, 1, 5, 2])
> decoder.5.0.imag_bias torch.Size([1])
> enhance1.real_lstm.weight_ih_l0 torch.Size([512, 512])
> enhance1.real_lstm.weight_hh_l0 torch.Size([512, 128])
> enhance1.real_lstm.bias_ih_l0 torch.Size([512])
> enhance1.real_lstm.bias_hh_l0 torch.Size([512])
> enhance1.imag_lstm.weight_ih_l0 torch.Size([512, 512])
> enhance1.imag_lstm.weight_hh_l0 torch.Size([512, 128])
> enhance1.imag_lstm.bias_ih_l0 torch.Size([512])
> enhance1.imag_lstm.bias_hh_l0 torch.Size([512])
> enhance2.real_lstm.weight_ih_l0 torch.Size([512, 128])
> enhance2.real_lstm.weight_hh_l0 torch.Size([512, 128])
> enhance2.real_lstm.bias_ih_l0 torch.Size([512])
> enhance2.real_lstm.bias_hh_l0 torch.Size([512])
> enhance2.imag_lstm.weight_ih_l0 torch.Size([512, 128])
> enhance2.imag_lstm.weight_hh_l0 torch.Size([512, 128])
> enhance2.imag_lstm.bias_ih_l0 torch.Size([512])
> enhance2.imag_lstm.bias_hh_l0 torch.Size([512])
> enhance2.r_trans.weight torch.Size([512, 128])
> enhance2.r_trans.bias torch.Size([512])
> enhance2.i_trans.weight torch.Size([512, 128])
> enhance2.i_trans.bias torch.Size([512])
> [*] Parameter Size: 3671917
> 
> the code will be open-source soon...

**Comment by huyanxin** [comment]
Yes, real+imag = (512+512), or you can use a 1024 linear layer; in my experiments, they worked like a little difference...

**Comment by kssk16** [comment]
Thank you :)

**Comment by huyanxin** [comment]
I update the codes in https://github.com/huyanxin/DeepComplexCRN/blob/master/dc_crn.py.

**Comment by kssk16** [comment]
> I update the codes in https://github.com/huyanxin/DeepComplexCRN/blob/master/dc_crn.py.

Thanks for this :)
