### ISSUE TITLE
No License file

### ISSUE THREAD

**Issue by 5ke** [huyanxin/DeepComplexCRN#5]
Thank you for posting your model. Could you consider adding a license file? Without it we can only look at the code. See also: https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/licensing-a-repository

**Comment by huyanxin** [comment]
Thank you for your reminder :). I have updated the Apache 2 license 
https://github.com/huyanxin/DeepComplexCRN/blob/master/LICENSE
